version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - xpack.security.authc.anonymous.username=anonymous
      - xpack.security.authc.anonymous.roles=superuser
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=password
      - xpack.security.http.ssl.enabled=false
    networks:
      - bha
    expose:
      - '9200'
    ports:
      - '127.0.0.1:9200:9200'

  nginx:
    image: nginx:latest
    hostname: nginx
    ports:
      - '127.0.0.1:8000:8000'
    networks:
      - bha
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  app:
    image: ghcr.io/banned-historical-archives/banned-historical-archives.github.io:latest
    depends_on:
      - elasticsearch
      - nginx
    networks:
      - bha
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      - NODE_ENV=development
      - ES_URL=http://elasticsearch:9200
      - ES_USERNAME=elastic
      - ES_PASSWORD=password
      # - node_options="--max-old-space-size=8192"
networks:
  bha:
    driver: bridge
