name: automated_entry
on:
  issues:
    types: [opened]

jobs:
  automated_entry:
    name: Automated entry
    if: ${{ startsWith(github.event.issue.title, '[自动化录入]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: 'YYYY-MM-DD-HH-mm-ss'
      - name: Set UUID
        id: generate-uuid
        uses: filipstefansson/uuid-action@v1
        with:
          name: prefix${{ env.GITHUB_ACTION }}${{ env.GITHUB_RUN_NUMBER }}${{ github.sha }}${{ steps.time.outputs.time }}
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
      - name: node init
        run: |
          npm i
      - id: get_safe_title
        run: echo ::set-output name=safe_title::$(npx ts-node --project ./tsconfig.build.json backend/gitworkflow-get-safe-title.ts)
        env:
          TITLE: ${{ github.event.issue.title }}
      - id: get_archive_id
        run: echo ::set-output name=archive_id::$(npx ts-node --project ./tsconfig.build.json backend/gitworkflow-get-archive-id.ts)
        env:
          BODY: ${{ github.event.issue.body }}
          TITLE: ${{ github.event.issue.title }}

      - run: git config --global http.postBuffer 2097152000
      - run: git config --global user.email "you@example.com"
      - run: git config --global user.name "Your Name"
      - run: mkdir -p raw
      - run: mkdir -p config

      - name: init subm raw
        uses: actions/checkout@v4
        with:
          repository: 'banned-historical-archives/banned-historical-archives${{ steps.get_archive_id.outputs.archive_id }}'
          ref: 'main'
          token: ${{ secrets.GH_PAT }}
          path: 'raw/archives${{ steps.get_archive_id.outputs.archive_id }}'
      - name: init subm config
        uses: actions/checkout@v4
        with:
          repository: 'banned-historical-archives/banned-historical-archives${{ steps.get_archive_id.outputs.archive_id }}'
          ref: 'config'
          token: ${{ secrets.GH_PAT }}
          path: 'config/archives${{ steps.get_archive_id.outputs.archive_id }}'
      - id: action_with_json_output
        run: npx ts-node --project ./tsconfig.build.json backend/gitworkflow-automated-entry.ts
        env:
          BODY: ${{ github.event.issue.body }}
          TITLE: ${{ github.event.issue.title }}
      - name: Create Pull Request For Raw
        run: |
          cd raw/archives${{ steps.get_archive_id.outputs.archive_id }}
          git checkout -b feat/${{ steps.generate-uuid.outputs.uuid }}
          git add .
          git commit -m "feat: [自动化录入]${{ steps.get_safe_title.outputs.safe_title}}"
          git push origin feat/${{ steps.generate-uuid.outputs.uuid }}
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
          https://api.github.com/repos/banned-historical-archives/banned-historical-archives${{ steps.get_archive_id.outputs.archive_id }}/pulls \
          -d "{
            \"title\": \"[自动化录入]${{ steps.get_safe_title.outputs.safe_title}}\",
            \"body\": \"https://github.com/banned-historical-archives/banned-historical-archives.github.io/issues/${{github.event.issue.number}}\",\"head\":\"feat/${{ steps.generate-uuid.outputs.uuid }}\",
            \"base\":\"main\"}"
      - name: Create Pull Request For Config
        run: |
          cd config/archives${{ steps.get_archive_id.outputs.archive_id }}
          git checkout -b feat/config-${{ steps.generate-uuid.outputs.uuid }}
          git add .
          git commit -m "feat: [自动化录入]${{ steps.get_safe_title.outputs.safe_title}}"
          git push origin feat/config-${{ steps.generate-uuid.outputs.uuid }}
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
          https://api.github.com/repos/banned-historical-archives/banned-historical-archives${{ steps.get_archive_id.outputs.archive_id }}/pulls \
          -d "{
            \"title\": \"[自动化录入]${{ steps.get_safe_title.outputs.safe_title}}\",
            \"body\": \"close https://github.com/banned-historical-archives/banned-historical-archives.github.io/issues/${{github.event.issue.number}}\",\"head\":\"feat/config-${{ steps.generate-uuid.outputs.uuid }}\",
            \"base\":\"config\"}"
