name: build-json
on:
  workflow_run:
    workflows: ['build']
    types: [completed]

permissions:
  contents: write
jobs:
  container-job:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
      - uses: actions/checkout@v4
        with:
          ref: 'indexes'
          path: 'tmp_indexes'
      - run: npm install
      - run: mv tmp_indexes/indexes ./
      - run: node_options="--max-old-space-size=8192" npm run init-parsed
      - run: node_options="--max-old-space-size=8192" npm run build-article-json
      - run: git config --global http.postBuffer 2097152000
      - run: git config --global user.email "you@example.com"
      - run: git config --global user.name "Your Name"
      - run: git checkout --orphan x
      - run: git reset --hard
      - run: git add json
      - run: git commit -m i
      - run: git push origin x:json -f
